version: '3'

services:

  joyreactor:
    container_name: joyreactor-parser
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: bridge
    volumes:
      - $PWD/:/joyreactor
    working_dir: /joyreactor
